# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- carlos

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'SonarCloud'
    organization: 'greivinmontoyaestrada'
    scannerMode: 'CLI'
    configMode: 'manual'
    cliProjectKey: 'greivinmontoyaestrada_Guanacaste-Digital'
    cliProjectName: 'Guanacaste Digital'
    cliSources: '.'
- task: SonarCloudAnalyze@1